#!/usr/bin/env bash
# Copy the collected assets into Remotion's public/ dir and regenerate the screen manifest.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
src="$here/../docs/Utsav/video/assets"
pub="$here/public"
mkdir -p "$pub/sfx" "$pub/screens"
cp "$src/flowchart/flowchart.png" "$pub/flowchart.png"
cp "$src/narration_s3.wav"        "$pub/narration.wav"
cp "$src"/sfx/*.wav                "$pub/sfx/"
cp "$src"/screens/*.png            "$pub/screens/"
# demo.png is a byte-copy of officer.png (the /demo route redirects); drop it.
rm -f "$pub/screens/demo.png"
{
  echo "/** Generated by scripts-sync-assets.sh — do not edit by hand. */"
  echo "export const SHOTS: Record<string, string | null> = {"
  for f in "$pub"/screens/*.png; do
    b="$(basename "$f")"
    echo "  '$b': 'screens/$b',"
  done
  echo "};"
  echo "export const shot = (name: string): string | null => SHOTS[name] ?? null;"
} > "$here/src/screens.ts"
echo "synced: $(ls "$pub/screens" | wc -l) screens, $(ls "$pub/sfx" | wc -l) sfx"
