/** Generated by scripts-build-s1-sources.py — do not edit by hand.
 *  Crops and highlight boxes come straight out of the source PDFs. */
export type HlRect = { x: number; y: number; w: number; h: number };
export type SourceShot = { src: string; aspect: number; hl: Record<string, HlRect[]> };
export const SOURCES: Record<string, SourceShot> = {
  "clause": {
    "src": "s1/clause.png",
    "aspect": 4.0961,
    "hl": {
      "interest": [
        {
          "x": 0.7953532726484611,
          "y": 0.14204041049678676,
          "w": 0.14829648894668407,
          "h": 0.12485352082667486
        },
        {
          "x": 0.08708279150411792,
          "y": 0.28479102304605725,
          "w": 0.7051495448634589,
          "h": 0.12485352082667486
        }
      ],
      "advert": [
        {
          "x": 0.29833116601647164,
          "y": 0.5724228543020496,
          "w": 0.5818335500650194,
          "h": 0.12485352082667486
        }
      ]
    }
  },
  "mandate": {
    "src": "s1/mandate.png",
    "aspect": 6.9112,
    "hl": {
      "seventy": [
        {
          "x": 0.3146427383915814,
          "y": 0.5021427240544065,
          "w": 0.3614538494028415,
          "h": 0.21837152971865095
        }
      ]
    }
  },
  "placement": {
    "src": "s1/placement.png",
    "aspect": 7.2523,
    "hl": {
      "certified": [
        {
          "x": 0.36194385763246895,
          "y": 0.3187149413564507,
          "w": 0.30419188433203925,
          "h": 0.17325344212136684
        }
      ],
      "placed": [
        {
          "x": 0.05713097063633791,
          "y": 0.6036460989291175,
          "w": 0.44053769683163024,
          "h": 0.17325344212136684
        }
      ]
    }
  },
  "concentration": {
    "src": "s1/concentration.png",
    "aspect": 4.6118,
    "hl": {
      "tenroles": [
        {
          "x": 0.05715892998272024,
          "y": 0.525995620082733,
          "w": 0.7733350672128338,
          "h": 0.11022791791710551
        }
      ]
    }
  },
  "tableb": {
    "src": "s1/tableb.png",
    "aspect": 2.306,
    "hl": {
      "green": [
        {
          "x": 0.029943648449110637,
          "y": 0.39827689253147475,
          "w": 0.10540600789704693,
          "h": 0.04933174888937164
        }
      ],
      "safai": [
        {
          "x": 0.4919311534950432,
          "y": 0.3985491428012834,
          "w": 0.1577008403488164,
          "h": 0.048569448133907005
        }
      ],
      "share": [
        {
          "x": 0.8912936566416928,
          "y": 0.39827689253147475,
          "w": 0.05309671052424444,
          "h": 0.04933174888937164
        }
      ]
    }
  }
} as const;
