/** Generated by scripts-build-s5-sources.py — do not edit by hand.
 *  Crops and highlight boxes come straight out of the source PDFs. */
import type { SourceShot } from './s1Sources';
export const SOURCES_S5: Record<string, SourceShot> = {
  "cagcover": {
    "src": "s5/cagcover.png",
    "aspect": 0.7071,
    "hl": {}
  },
  "pmcover": {
    "src": "s5/pmcover.png",
    "aspect": 0.6657,
    "hl": {
      "title": [
        {
          "x": 0.41516227282812596,
          "y": 0.17485616075085098,
          "w": 0.16973596627468382,
          "h": 0.023605078180072632
        }
      ]
    }
  },
  "gazette": {
    "src": "s5/gazette.png",
    "aspect": 2.3233,
    "hl": {
      "notified": [
        {
          "x": 0.05295817868187255,
          "y": 0.8657568214728514,
          "w": 0.5673689953165416,
          "h": 0.04906349672058223
        }
      ]
    }
  },
  "nqr": {
    "src": "s5/nqr.png",
    "aspect": 9.5635,
    "hl": {
      "record": [
        {
          "x": 0.5802312433869498,
          "y": 0.12552001147611552,
          "w": 0.37101930748182543,
          "h": 0.18591306842633684
        },
        {
          "x": 0.09892388216013162,
          "y": 0.39018792138861036,
          "w": 0.32864028636476406,
          "h": 0.18591306842633684
        }
      ]
    }
  }
} as const;
