/** Generated by scripts-sync-assets.sh — do not edit by hand. */
export const SHOTS: Record<string, string | null> = {
  'chat.png': 'screens/chat.png',
  'home.png': 'screens/home.png',
  'interview.png': 'screens/interview.png',
  'myplan.png': 'screens/myplan.png',
  'officer.png': 'screens/officer.png',
  'onboarding.png': 'screens/onboarding.png',
  'outcomes.png': 'screens/outcomes.png',
  'settings.png': 'screens/settings.png',
  'state.png': 'screens/state.png',
};
export const shot = (name: string): string | null => SHOTS[name] ?? null;
