/** Generated by assets/sfx_soft/generate_soft_sfx.py — seconds from file start to its loudest point. */
export const SFX_PEAK: Record<string, number> = {
  'chime.wav': 0.0126,
  'click.wav': 0.0037,
  'confirm.wav': 0.0112,
  'drag.wav': 0.1324,
  'keypad.wav': 0.0042,
  'notify.wav': 0.01,
  'pop.wav': 0.004,
  'ring.wav': 0.0461,
  'send.wav': 0.0104,
  'slide.wav': 0.095,
  'tick.wav': 0.0031,
  'whoosh.wav': 0.1736,
  'whoosh_lo.wav': 0.2301,
};

/**
 * Where to *place* a sound so it is *heard* on the beat.
 *
 * A whoosh that peaks 174ms in will sound a third of a beat late if you start it
 * on the frame the motion starts. Every cue is therefore pulled earlier by its own
 * peak offset. This is the fix for the lag in the first cut.
 */
export const cueFrame = (relSeconds: number, file: string, fps: number): number =>
  Math.round(relSeconds * fps) - Math.round((SFX_PEAK[file] ?? 0) * fps);
